### ISSUE TITLE
Incorrect release comment

### ISSUE THREAD

**Issue by steveoh** [agrc/release-issue-notifications-action#34]
From release https://github.com/agrc/atlas/releases/tag/v5.6.1-0 this comment was generated
https://github.com/agrc/atlas/issues/469#issuecomment-2384302953. But that issue is not in the release and shouldn't be notifying. It has a prior notification from another release.

**Comment by stdavis** [comment]
This is a hard one. I wonder if we should just not run this action for prereleases. Because it's hard to know what the last release to check against should be. Currently, if the action is running on a prerelease, it uses the last prerelease as the last release to check against. Maybe the last prod release should always be the last release to check against? Then, you would get double-notifications for subsequent prereleases.

I vote that we recommend that this not be used for prereleases and ignore the bug. Do you feel differently?

**Comment by steveoh** [comment]
That works for me.
